version: '2'
services:
  jhi_oauth2_app1-mysql:
    image: mysql:5.7.13
    # volumes:
    #     - ~/volumes/jhipster/jhi_oauth2_app1/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=jhi_oauth2_app1
    ports:
      - 3307:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
